services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb://mongo:27017/authapp"
      PORT: 3001
      JWT_SECRET: super_secret_key
      REFRESH_SECRET: super_secret_refresh

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"

volumes:
  mongo-data: